version: "2"

services:
  namenode:
    image: bde2020/hadoop-namenode:1.0.0-hadoop2.7.1
    container_name: namenode
    networks:
      - sparklify
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.1.0
    networks:
      - sparklify
  spark-master:
    image: bde2020/spark-master:2.0.0-hadoop2.7-hive
    networks:
      - sparklify
    container_name: spark-master
    ports:
      - "8080:8080"
    env_file:
      - ./hadoop-hive.env

networks:
  sparklify:
    external:
      name: sparklify
